### PR TITLE
Upgrade To PHP CS Fixer 1.7

### PR DESCRIPTION
**Pull request by GrahamCampbell**
WIP

### CODE REVIEW

**Comment by crynobone** [comment]
Missing `phpdoc_no_access` as well.

**Comment by GrahamCampbell** [comment]
@crynobone Yeh, I know, I wrote that fixer. :)

**Comment by crynobone** [comment]
Yeah, but it hard to debug `StyleCI\Config\Exceptions\InvalidFixerException` error thrown when I accidentally add unsupported (future released) fixers.

**Comment by GrahamCampbell** [comment]
Why is it hard to debug? The invalid fixer exception message contains the name of the invalid fixer, and a getter method for the fixer name is also provided on the exception?

**Comment by crynobone** [comment]
@GrahamCampbell Here's an example. 

https://styleci.io/commits/141466e7a2346c9ad0dc603e78c128820c74269d doesn't explain much other than "The StyleCI checks were misconfigured"

screen shot 2015-04-19 at 11 11 12 pm

It was due to https://github.com/jomweb/platform/blob/141466e7a2346c9ad0dc603e78c128820c74269d/.styleci.yml#L22

**Comment by GrahamCampbell** [comment]
Right, yeh. We're open to pulls that present more information about errors to the user. :)

**Pull request merged**
